### ISSUE TITLE
Allow translating stable versions

### ISSUE THREAD

**Issue by zedejose** [professionalthemes/Subtitles#15]
I propose to move translations to http://wp-translations.org/developers-wp-translations/, so that strings can be kept in sync with current versions, instead of always one behind.

**Comment by philiparthurmoore** [comment]
Closing this out since, after long last, [this](https://make.wordpress.org/plugins/2015/12/06/plugin-translations-for-all-plugins/) is a thing now. Should be able to handle translations for this plugin on .org when I make the next commit/release.
