### ISSUE TITLE
Add support for shortcodes.

### ISSUE THREAD

**Issue by philiparthurmoore** [professionalthemes/Subtitles#52]
See https://wordpress.org/support/topic/nativae-support-for-shortcode-use?replies=3

**Comment by philiparthurmoore** [comment]
Don't think this is a priority right now. Closing.

**Comment by nicoleamandaa** [comment]
I'd love this eventually if it doesn't yet exist!

**Comment by philiparthurmoore** [comment]
Not yet, but could you give me a use case where this would make sense? I'd totally be up for considering adding it in if it made sense! Cheers.

**Comment by nicoleamandaa** [comment]
I'm in the process of writing all my default title and meta descriptions, instead of having the excerpt it would be more useful SEO wise for me to do "%%Subtitle%% photos by Nicole Amanda Photography" so that it would show up in search as "Pink & Grey Holiday Inn Wedding photos by Nicole Amanda Photography"

**Comment by philiparthurmoore** [comment]
Do you mean a Yoast-specific template tag for better SEO? I thought you meant a shortcode to be used in post content, which was confusing.

**Comment by nicoleamandaa** [comment]
Oh I figured it was universal, wordpress newb. But yes!

**Comment by philiparthurmoore** [comment]
Okay, can you email support@professionalthemes.nyc and I'll get back to you Monday about both of your issues? I need to see if Yoast has an API we can plug into. Thanks a ton.

**Comment by philiparthurmoore** [comment]
@nicoleamandaa, heads up that I responded about the Yoast shortcode issue in a separate email. We could probably do it as a custom project but don't currently have the manpower to invest in adding this into the .org plugin at the moment. It's a fantastic suggestion and I'd love to get it in; we simply just don't have the staff available for working on it outside of a customized plugin project. I'll create an Enhancement ticket for shortcodes, though, so I can notify you when or if we can get them into _Subtitles_.
