### ISSUE TITLE
Adding Subtitles to RSS

### ISSUE THREAD

**Issue by pchrismac** [professionalthemes/Subtitles#61]
So, I know you took this out about a year ago, Subtitles showing up in RSS. Subtitles are becoming important in other places as well.

For example, I've setup an email campaign built from the RSS. My titles are okay, but it would really help to have that Subtitle punch. Is there some way to get it back into the RSS? Maybe even just a code fix? 

Thanks for your help.

**Comment by philiparthurmoore** [comment]
@pchrismac Sheesh. So sorry to have missed this Issue. For now, you can [remove this](https://github.com/philiparthurmoore/Subtitles/blob/9bd96bbdd7ccba8c31c2fb8ecaa6eebfc14b19ba/public/class-subtitles.php#L568) portion of the plugin and they will show up in feeds just fine. I'll add in a way to filter this output in the next version of the plugin.

**Comment by pchrismac** [comment]
Thanks for this. Do I just paste the new code over the old default code? Add it CSS? Or something else? I've tried a couple but keep messing it up. Not really a coder. Thanks.

**Comment by philiparthurmoore** [comment]
@pchrismac, see [this](https://github.com/professionalthemes/Subtitles#displaying-subtitles-in-rss-feeds). Put it into your theme's `functions.php` file and you should be good to go.
