### ISSUE TITLE
the_title() returning title AND subtitle!

### ISSUE THREAD

**Issue by fuyangli** [professionalthemes/Subtitles#63]
I'm using the_title() in my loop with the_subtitle() in another area.
Is there an way so the_title does not return the subtitle?

Thanks in advance!

**Comment by philiparthurmoore** [comment]
Hi there. Yes, you could disable automatic Subtitle output by just having [this](https://github.com/philiparthurmoore/Subtitles#modifying-supported-subtitles-views) return false at all times.

Cheers,
Philip
