### ISSUE TITLE
works fine: want to limit width

### ISSUE THREAD

**Issue by Dindigul** [professionalthemes/Subtitles#64]
Hello
**The plugin works fine**. However, I would appreciate if you tell me how to limit its width upto 3/4 of page width. (Reason being, I don't want to use sidebar, and without it the subtitle stretches to full width).

**Comment by philiparthurmoore** [comment]
Hi there. Try this:

```css
.entry-subtitle { max-width: 75%; }
```

Cheers,
Philip

**Comment by Dindigul** [comment]
Worked perfectly.

BTW, can it be used to apply selectively? I mean only to Pages and Not Posts? Or on desired Pages/Posts? 

(I also want my rating to change to 5 stars from present three. How to do that? I apologize for that knee-jerk reaction!)

**Comment by philiparthurmoore** [comment]
Hi @Dindigul. Thanks for reconsidering your review. Often times those reviews are what keeps me going, and a simple support request can go a long way to helping you figure out your problem.

Yes, you can apply that code selectively, but I would need to know the specific posts/pages that you wanted to selectively apply the code on. Here's how you can easily do that:

1. Inspect your page HTML: https://cloudup.com/cBPQt_NgQq8
2. Use that post class in front of the CSS I gave you, for example `.post-400 .entry-subtitle { max-width: 75%; }`.

You can also use [this plugin](https://wordpress.org/plugins/reveal-ids-for-wp-admin-25/) to easily tell you which post/page ID you're using to easily set up post/page specific CSS.

Cheers,
Philip
