### ISSUE TITLE
Getting just the (actual) title?

### ISSUE THREAD

**Issue by matthauger** [professionalthemes/Subtitles#65]
There's probably an easy answer to this, but how do I get just the title (esp. a clean version of the title), without the subtitle included? I'd like to, for example, set the title attribute of my permalinks to show just the title, sans subtitle.

**Comment by philiparthurmoore** [comment]
>  I'd like to, for example, set the title attribute of my permalinks to show just the title, sans subtitle.

This indicates to me that you're using `the_title` in an attribute when you should NEVER do that. Read [https://github.com/professionalthemes/Subtitles#theres-weird-html-showing-up-on-my-site](this). In short, use `the_title_attribute` and you'll be set. Never use the_title in your attributes. That's not why it was created.

Hope that helps. :)

**Comment by matthauger** [comment]
Thanks, Philip! But I *am* using `the_title_attribute`; it seems to return *both* the title and the subtitle, concatenated. I'm looking to get just the title, sans the subtitle.

**Comment by philiparthurmoore** [comment]
Seriously? That shouldn't be happening at all. Could you please show me your code? I'll take a look first thing in the morning. Thanks so much.

**Comment by matthauger** [comment]
There's not much to the code here:
    <a href="<?php the_permalink(); ?>" title="<?php echo esc_attr( sprintf( __( 'Permalink to “%s”', 'independent-publisher' ), the_title_attribute( 'echo=0' ) ) ); ?>" rel="bookmark"><?php the_title(); ?></a>

**Comment by matthauger** [comment]
There's not much to the code here:

`<a href="<?php the_permalink(); ?>" title="<?php the_title_attribute() ?>" rel="bookmark"><?php the_title(); ?></a>`

**Comment by philiparthurmoore** [comment]
I might be going crazy here. Let me verify this first thing in the morning for you. Pretty sure there's an easy way around this.

**Comment by matthauger** [comment]
Any luck, Philip? Thanks so much for taking a look at this!

**Comment by philiparthurmoore** [comment]
Super-busy. I promise to take a look at this today! Cheers. :)

**Comment by matthauger** [comment]
Thanks, Philip, and thanks again for your sweet plugin.

**Comment by philiparthurmoore** [comment]
@matthauger, sorry for the delay on this. [This](http://wordpress.stackexchange.com/questions/57079/how-to-remove-a-filter-that-is-an-anonymous-object) is exactly how to handle what you're after, but it's somewhat convoluted and complicated. Since (I incorrectly stated the opposite) `the_title_attribute` returns both title and subtitle, you'll need to do a little bit of work via `var_dump($GLOBALS['wp_filter'][ 'the_title' ]);` to figure out how to remove the filter inline. I'll document this a bit better moving forward but for now there is, unfortunately, no super-quick fix for this.

**Comment by matthauger** [comment]
I appreciate your diligence here, and I'll try to dive into the solution you linked to. FWIW, I'd love to see `the_real_title_attribute or something equivalent in the plugin to make this easy on us end-users. Thanks again!

**Comment by deviodigital** [comment]
I might be a bit late to the party, but I've been using `single_post_title` in a theme I'm developing and it's displaying just the title.

**Comment by philiparthurmoore** [comment]
@deviodigital, That also wouldn't work in this case since the plugin is also filtering `single_post_title`. One solution might be this: turn off Subtitles for `single_post_title` and leave it turned on for just `the_title`; this would be a quick and dirty way of achieving what @matthauger is after.

```php
				add_filter( 'the_title', array( &$this, 'the_subtitle' ), 10, 2 );

				/**
				 * Let's also filter the dedicated function for single post titles
				 *
				 * @link https://github.com/professionalthemes/Subtitles/issues/2
				 *
				 * @since 1.0.1
				 */
				add_filter( 'single_post_title', array( &$this, 'the_subtitle' ), 10, 2 );
```

**Comment by deviodigital** [comment]
If the permalinks are being manually written in code, then `single_post_title()` would work, like this

`<a href="<?php the_permalink(); ?>" title="<?php single_post_title(); ?>"></a>`

I've tested it on a couple of different themes to verify, and it does work.

**Comment by philiparthurmoore** [comment]
Technically you probably should never do that: `the_title_attribute` is more appropriate. :) It should also be run through `esc_attr`. Anyway... bed time. I'll revisit this later. My head is spinning.

**Comment by philiparthurmoore** [comment]
After looking at this much later, it appears to be that you can simply remove `the_subtitle` from `single_post_title` via `remove_filter` and get rid of this issue altogether. Are either of you still dealing with this? If not, I'll close this out.

**Comment by matthauger** [comment]
If I'm remembering correctly, I've built my own workaround for this. Thanks for the follow-up!

**Comment by philiparthurmoore** [comment]
Wonderful. Thanks for confirming!

**Comment by anddorua** [comment]
Here is my inline workaround
```
<?php
    remove_post_type_support( 'page', 'subtitles' );
    the_title_attribute();
    add_post_type_support( 'page', 'subtitles' );
?>
```

**Comment by philiparthurmoore** [comment]
Love it. Thanks for contributing that information! 👍
