### ISSUE TITLE
Ampersand show encoded in Backend

### ISSUE THREAD

**Issue by kraftner** [professionalthemes/Subtitles#66]
If you create a subtitle that includes the `&` character it will show as `&amp;` in the backend after saving. In the frontend all is fine.

**Comment by kraftner** [comment]
Looks like the issue is with `htmlspecialchars` [here](https://github.com/professionalthemes/Subtitles/blob/master/admin/subtitles-admin.php#L185)

**Comment by philiparthurmoore** [comment]
You're right. I think there's a reason I used `htmlspecialchars` but seeing `&amp;` is obviously not very nice. I'll fix this in the next release; should have it out in the next week or two, before 4.4 lands. Thanks so much for the heads up.

**Comment by kraftner** [comment]
I don't really see a reason for it. This is going through `esc_attr`anyway which does `htmlspecialchars` anyway. So it is actually converted twices -> `&amp;amp;`

I'll do a PR.

**Comment by philiparthurmoore** [comment]
Wonderful, thank you thank you.

**Comment by philiparthurmoore** [comment]
Will merge this in at some point during the weekend. Thanks again for this.

**Comment by kraftner** [comment]
Awesome. Thank **you**  for the plugin. :smile:

**Comment by kraftner** [comment]
Anything else I can do here?

**Comment by philiparthurmoore** [comment]
Nope. Incredibly swamped today prepping a new theme for launch. I expect to merge this in within the next day or two. 4.4 is dropping tomorrow. I'll be updating this either tomorrow or the day after and releasing. Cheers.
