### ISSUE TITLE
Subtitles not appearing in previews.

### ISSUE THREAD

**Issue by philiparthurmoore** [professionalthemes/Subtitles#69]
Ref: https://wordpress.org/support/topic/subtitles-not-appearing-in-previews

Need to look into this.

**Comment by philiparthurmoore** [comment]
@mkrdip, can you verify this bug for me?

**Comment by mkrdip** [comment]
Synapse is a premium theme, I was unable to check the plugin preview with that theme he mentioned: https://www.simplethemes.com/wordpress-themes/theme/synapse

It doesn't have the issue he mentioned with default themes **twenty** series:
![image](https://cloud.githubusercontent.com/assets/3819579/12761522/87abbd0c-ca15-11e5-9b4d-e27f64d5d6e6.png)

**Comment by philiparthurmoore** [comment]
Great. Thanks.
