### ISSUE TITLE
Subtitles don't get passed to Facebook OG

### ISSUE THREAD

**Issue by theyoungrens** [professionalthemes/Subtitles#74]
Possible to rewrite og:title to include the subtitle text with a delimiter?

**Comment by philiparthurmoore** [comment]
@theyoungrens, apologies for my delayed response on this issue. This is probably possible already via the API that's available within the plugin, but I wouldn't be able to say 100% for sure without diving into the issue more. As you noted in your email, this is more of a side project for us than our super-primary focus, but it doesn't mean that we're not open to developing this out further to fit your needs. Can you please shoot me an email at services (at) professionalthemes (dot) nyc and give me a little bit more information to go on, for example your site URL, an example blog post that you're sharing to Facebook, what's missing from the Facebook share, and how Subtitles can help you share out your post the way you need it do?

Thanks, and sorry again. We've been crazy-swamped and I generally do an Issue sweep of Subtitles every now and then but not daily.

**Comment by philiparthurmoore** [comment]
Closing this out - see the above comment.
