### ISSUE TITLE
Change to H2?

### ISSUE THREAD

**Issue by nicoleamandaa** [professionalthemes/Subtitles#75]
Hello,
I have tried to do some reading and research to figure out myself prior to posting here. I know it says in the code the reasoning for it being an H1 span, but I would really like it to inherit my H2 settings. I'm a code newb but is there any minor code I can add/change so that my Subtitles show up as H2?
TIA!

**Comment by philiparthurmoore** [comment]
Hi Nicole. There are a number of ways to do this. Could you please post the code that your theme uses to output titles and I'll give you some suggestions? I'm heading down for the night, but will check in on this tomorrow. Thanks a ton.

**Comment by nicoleamandaa** [comment]
I think I figured it out! Sound the code spot in the plugin code. Thanks!

Nicole Salter
*Nicole Amanda Photography*

*Office hours: Tuesday-Friday 9:00am-5:00pm*

Ottawa & destination wedding photographer
website: www.nicoleamanda.ca
<http://www.nicoleamanda.ca/?utm_source=email&utm_medium=email&utm_term=email&utm_content=email&utm_campaign=email>
 |
 blog: blog.nicoleamanda.ca
<http://blog.nicoleamanda.ca/?utm_source=email&utm_medium=email&utm_term=email&utm_content=email&utm_campaign=email>
Instagram <http://instagram.com/nicoleamandaa> - Facebook
<http://www.facebook.com/nicolesalterphoto> - Twitter
<http://www.twitter.com/nicoleamandaa> - Pinterest
<http://www.pinterest.com/nicoleamandawp> - Google+
<http://google.com/+NicoleAmandaCA>

*Sign up for my newsletter here <http://eepurl.com/beM_2b>!*

**Comment by philiparthurmoore** [comment]
Fantastic. Thanks for letting me know! I'll close this issue out but do feel free to reach out again if you run into any other problems.

**Comment by nicoleamandaa** [comment]
Small additional question, where can I change the name/title that shows up on the top of a browser tab? I've tried to change in my Yoast but it seems subtitles is overriding something.

Right now its showing PageName[nospace]Subtitle | Title

Ideally I'd like to have Subtitle | Title | PageName

Thanks!

![screenshot 2016-05-04 15 32 46](https://cloud.githubusercontent.com/assets/10685320/15026764/046b088a-120e-11e6-88f7-3299a512e3d1.png)

**Comment by philiparthurmoore** [comment]
@nicoleamandaa, I believe that may have more to do with your theme than this plugin. Within Yoast SEO, have you tried to force title rewriting? That's what I usually do on my site if I add a unique site title via Yoast and it's not working. I believe there's an option to fix that. Failing that - you may need to get in touch with your theme author to let them know that you're unable to set your site title properly.

Subtitles doesn't touch titles that show up in the browser tab, only titles that show up on the page.

**Comment by nicoleamandaa** [comment]
No, my subtitle is in it and my theme doesn't support subtitles at all.
"Mer Bleue Bog Engagement" is my subtitle

Nicole Salter
*Nicole Amanda Photography*

*Office hours: Tuesday-Friday 9:00am-5:00pm*

Ottawa & destination wedding photographer
website: www.nicoleamanda.ca
<http://www.nicoleamanda.ca/?utm_source=email&utm_medium=email&utm_term=email&utm_content=email&utm_campaign=email>
 |
 blog: blog.nicoleamanda.ca
<http://blog.nicoleamanda.ca/?utm_source=email&utm_medium=email&utm_term=email&utm_content=email&utm_campaign=email>
Instagram <http://instagram.com/nicoleamandaa> - Facebook
<http://www.facebook.com/nicolesalterphoto> - Twitter
<http://www.twitter.com/nicoleamandaa> - Pinterest
<http://www.pinterest.com/nicoleamandawp> - Google+
<http://google.com/+NicoleAmandaCA>

*Sign up for my newsletter here <http://eepurl.com/beM_2b>!*

**Comment by philiparthurmoore** [comment]
Yikes, okay. Let me do some digging today and get back to you.

**Comment by philiparthurmoore** [comment]
@nicoleamandaa, I just ran another test on this and this does not appear to be an issue with _Subtitles_, but possibly your theme or a conflicting plugin. What happens if you switch over to Twenty Sixteen or another default theme? Do you still see the subtitle in your address bar? This is the standard header that we use in our themes:

```php
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="http://gmpg.org/xfn/11">
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
	<?php wp_head(); ?>
</head>
```

The actual title is handled from within our theme's setup file:

```php
	/**
	 * Let WordPress manage the document title.
	 * By adding theme support, we declare that this theme does not use a
	 * hard-coded <title> tag in the document head, and expect WordPress to
	 * provide it for us.
	 */
	add_theme_support( 'title-tag' );
```

Using this approach results in the following output:

<img width="1440" alt="subtitles-title-test" src="https://cloud.githubusercontent.com/assets/28684/15366230/8e071fda-1d4d-11e6-85a3-9f173024768c.png">

I've also tested this with a default theme and everything looks fine:

<img width="1440" alt="2016-05-18_23-11-04" src="https://cloud.githubusercontent.com/assets/28684/15366318/f78df9b0-1d4d-11e6-840d-d170abd8fd8c.png">

As this doesn't appear to be an issue with _Subtitles_, I'll close this issue out again, but feel free to update it with any additional information that you find out from either your theme developer or from Yoast. (Try disabling that also and seeing if the subtitle shows up in your title bar.)

**Comment by nicoleamandaa** [comment]
Hmm too scared to attempt. My theme is build and updated elsewhere, doesn't save directly into themes so can't risk losing it. It worked before so probably a plugin. Thanks!
