### ISSUE TITLE
Multilanguage problem

### ISSUE THREAD

**Issue by Subco** [professionalthemes/Subtitles#76]
Hi,

I just noticed that the subtitle cannot be placed individually for different languages any more. Since the last WP update the subtitle for our german site and english site are always the same. That means, if I change the subtitle in the german post the english post has the same subtitle and if I change it back in the english post the german post has the english subtitle.

**Comment by philiparthurmoore** [comment]
Hi there. Are you using a 3rd-party plugin for your multilingual site?

**Comment by Subco** [comment]
I just wanted to write that the problem maybe caused by "MultilingualPress". They updated their plugin yesterday.

**Comment by philiparthurmoore** [comment]
Yeah, my hunch is that this may be a problem on their end. We haven't changed anything with regard to our translations, which are super-simple. You might want to contact them and ask if they've changed anything in the last release that may be affecting the translation of custom fields?

**Comment by Subco** [comment]
Yes I think so too. It seems that you have to "remove" the relationship between the german and the english post (that function is provided by MultilingualPress). So you have to create two separated posts in german and english. Then the subtitle is also saved separately for each post.

Thank you nonetheless, I've complained to early, sorry ;)

**Comment by philiparthurmoore** [comment]
No worries at all. I'll close this out but feel free to open any other threads if you run into future issues. Have a wonderful day!
