### ISSUE TITLE
Subtitles for Categories

### ISSUE THREAD

**Issue by isaumya** [professionalthemes/Subtitles#83]
Hi there,
first of all thanks a lot for making this awesome plugin.  I think it would be great if this plugin allows to add subtitle for categories too. Because in wordpress categories can have their own archival pages. be it normal post category or category created by plugins like Easy Digital Downloads.

So, I think it would be really great if this plugin allows adding subtitle for each categories in near future release.

Keep up the good work.

**Comment by philiparthurmoore** [comment]
I'm not sure how I missed responding to you. I'm so sorry. Categories already do this though, but they are called descriptions. Check it out:

![2017-05-16_02-12-40](https://cloud.githubusercontent.com/assets/28684/26074759/36e8aa2c-39dd-11e7-8071-0dd597a69f82.png)

Cheers,
Philip
