### ISSUE TITLE
Meta Key

### ISSUE THREAD

**Issue by davidsherlock** [professionalthemes/Subtitles#86]
Hello,

I use EDD + Frontend Submissions and want to make it possible for the vendors to add subtitles to their product posts. FES allows you to create custom fields for the vendors and associate a meta key.

What is the meta key that Subtitles uses so I can set this up for my vendors?

Thanks,
David

**Comment by davidsherlock** [comment]
Got it! For anyone interested it's "_subtitle".

**Comment by philiparthurmoore** [comment]
You're quick! And you're exactly right. 😄
