### ISSUE TITLE
Title and subtitle appearing as part of featured image

### ISSUE THREAD

**Issue by videcollective** [professionalthemes/Subtitles#87]
<img width="819" alt="screen shot 2017-01-03 at 12 49 20" src="https://cloud.githubusercontent.com/assets/24893115/21607039/d3d1b74e-d1b3-11e6-9ea1-e093ff3e890e.png">

Hi, 

I'm having a problem with the title and subtitle appearing as part of the featured image after installing the Subtitle plugin. What can I do to fix this?

**Comment by philiparthurmoore** [comment]
Hi there. Have you read [this](https://github.com/professionalthemes/Subtitles#theres-weird-html-showing-up-on-my-site) yet? It tackles the issue you've raised.

**Comment by videcollective** [comment]
Yes, I did read it, but unfortunately I don't understand how to fix it as I'm not very good at coding.
It seems that I need to change "the_title" to "the_title_attribute" somewhere - the problem is that I don't know which template I need to edit, since I don't know where to find "the_title"..  Is this something that I should ask the theme developer about?

**Comment by philiparthurmoore** [comment]
This definitely sounds like something your theme developer should be able to fix for you. Ask them to make this quick adjustment for you and fix their themes and you should be all set. :-)
