### ISSUE TITLE
Recent Post Widget Extended - HTML issue

### ISSUE THREAD

**Issue by marcchaperon** [professionalthemes/Subtitles#88]
Hello,

Thanks for this amazing plugin,
My template wasn't compatible with the plugin but I've successfully change the title by title attribute.
But I have no luck with the plugin "Recent Post Widget Extended" the bad html display is here once again :'(.
I found this line on the fonction code of the plugin  👍
`$html .= '<h3 class="rpwe-title"><a href="' . esc_url( get_permalink() ) . '" title="' . sprintf( esc_attr__( 'Permalink to %s', 'recent-posts-widget-extended' ), the_title_attribute( 'echo=0' ) ) . '" rel="bookmark">' . esc_attr(get_the_title()) . '</a></h3>';
`
If I delete that line, the title is gone. So... I wonder if I can tell the fonction.php of this plugin to allow html :)

Can you help me on that ?

Thanks !!

**Comment by mkrdip** [comment]
Hi @marcchaperon, 

Would you mind to get in touch with RPWE support [here](https://wordpress.org/support/plugin/recent-posts-widget-extended) for this and let us know what they suggest?
