### ISSUE TITLE
Subtitles doesn't work with Virtue theme

### ISSUE THREAD

**Issue by betwinned** [professionalthemes/Subtitles#90]
Hello.  We are a high school newspaper and have been using Subtitles regularly since 2014, so ... thank you.  We just switched to the theme [Virtue](https://themes.kadencethemes.com/virtue/) and see that the subtitles render properly on the post page, but not in the blog overview on the homepage.  See the attached screenshots (one is the post page; one is the home page display with error; another is an example of a home page display without error).  I wasn't sure where to start troubleshooting - with you, or with the theme developers.  I decided to start with you.  Any information you could provide would be great.  I know I can use custom fields to create subtitles, but since we have already created so many subtitles with your plugin, I'd rather continue to use it, rather than to dump it.

Please inform.

Thank you in advance,
Diana
![pluginissue1](https://cloud.githubusercontent.com/assets/27427861/25008605/438ade04-2032-11e7-8d1d-e5dd4fb5959b.JPG)
![pluginissue2](https://cloud.githubusercontent.com/assets/27427861/25008604/438aa65a-2032-11e7-8266-35bf39688021.JPG)
![pluginissue3](https://cloud.githubusercontent.com/assets/27427861/25008603/438a423c-2032-11e7-8e66-bfccc79409a2.JPG)

**Comment by betwinned** [comment]
Hi, sorry, I didn't include the link to our site.  [MFS WordsWorth](http://www.mfswordsworth.com).  Thanks again.

**Comment by mkrdip** [comment]
Hi Diana [@betwinned], 

Thanks for creating the issue but it'd be considered as a support request. It's not a plugin issue, as it is working fine with all other themes but not only with your new theme. I would request you to get in touch with us via support@professionalthemes.nyc. So, I can help you in detail and ask more questions, which are not suitable to ask here in public repo.
